#GCP Deploy New Instance playbook

- name: Deploy New GCP Instance
  hosts: 127.0.0.1
  connection: local
  vars:
    gcp_project: project-name-197116
    gcp_cred_kind: serviceaccount
    gcp_cred_file: "/home/user/serviceaccount-key.json"

  tasks:

  - name: create a disk
    gcp_compute_disk:
      name: ansible-test-gcp-disk
      size_gb: 50
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts
      zone: europe-west1-b
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk

  - name: create a address
    gcp_compute_address:
      name: ansible-test-gcp-ip
      region: europe-west1
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      network_tier: PREMIUM
      state: present
    register: address

  - name: create a instance
    gcp_compute_instance:
      name: ansible-test-gcp-vm
      machine_type: n1-standard-2
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      labels:
        environment: testing
        owner: alex_casado
        os: ubuntu-1804-lts
      network_interfaces:
      - network:
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      zone: europe-west1-b
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present